default-profiles = [
    "JaneDoe",
    "JackHowe",
    "BobSmith"
]

output-dir = { expr = "f'results/run-{datetime.now().strftime(\"%d-%m-%Y-%H.%M.%S\")}'" }

[env]
# Used in the robot file to determine whether headless should be true or false. 
# Fallback is the value of this variable => show the UI
ROBOTMK_HEADLESS_HOST="false"

# See https://practicesoftwaretesting.com/checkout for the user accounts

[profiles.JaneDoe]
description = "User Jane Doe"
[profiles.JaneDoe.extend-variables]
USER_NAME = "Jane Doe"
USER_EMAIL = "customer@practicesoftwaretesting.com"
USER_PASSWORD = "crypt:An2Yut93dNrtM3ayVVCnmspsRx5n/K98yesZtAou0Fr0Wkch3BDrdkRip2sNfdY0uf7SSKup7R4Q"

[profiles.JackHowe]
description = "User Jack Howe"
[profiles.JackHowe.extend-variables]
USER_NAME = "Jack Howe"
USER_EMAIL = "customer2@practicesoftwaretesting.com"
USER_PASSWORD = "crypt:An2Yut93dNrtM3ayVVCnmspsRx5n/K98yesZtAou0Fr0Wkch3BDrdkRip2sNfdY0uf7SSKup7R4Q"

[profiles.BobSmith]
description = "User Bob Smith"
[profiles.BobSmith.extend-variables]
USER_NAME = "Bob Smith"
USER_EMAIL = "customer3@practicesoftwaretesting.com"
USER_PASSWORD = "crypt:+sGGKbSxC8zUzxUF/1Ag+WoUakwCqwRH/RiMDgbD21E607H4OrfLcBj0MKVpYDyrwq0So1WBOg=="
