channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip=23.2.1
  - nodejs=22.11.0
  - pip:
      - robotframework==7.4
      - robotframework-browser==19.14.2
      - robotframework-crypto==0.3
      - robotframework-requests==0.9.7
      - robotframework-doctestlibrary==0.33.0

# Install Browser Library binaries after environment creation.
rccPostInstall:
  - rfbrowser init chromium
